site_name: Ayuda de DISMTools
theme: readthedocs
nav:
- Inicio: index.md
- Comienzo: getting_started/start.md
- Operaciones con imágenes:
  - Resumen: img_tasks/img_tasks.md
  - Modo de administración de imágenes en línea: img_tasks/online_inst_mgmt.md
  - Modo de administración de imágenes fuera de línea: img_tasks/offline_inst_mgmt.md
  - Administración de imágenes:
#    - Overview: img_tasks/mgmt.md
    - Aplicar una imagen: img_tasks/mgmt/apply_image.md
    - Capturar una imagen: img_tasks/mgmt/capture_image.md
    - Eliminar archivos de volumen de un archivo de imagen: img_tasks/mgmt/delete_image.md
    - Montar una imagen: img_tasks/mgmt/mount_image.md
    - Remontar una imagen: img_tasks/mgmt/remount_image.md
    - Dividir una imagen: img_tasks/mgmt/split_image.md
    - Desmontar una imagen: img_tasks/mgmt/unmount_image.md
    - Diálogos de información de imagen:
      - Resumen: img_tasks/info/infodlgs.md
      - Información de archivos de imagen: img_tasks/info/img_info.md
      - Información de paquetes: img_tasks/info/pkg_info.md
      - Información de características: img_tasks/info/feat_info.md
      - Información de paquetes AppX: img_tasks/info/appxpkg_info.md
      - Información de funcionalidades: img_tasks/info/cap_info.md
      - Información de controladores: img_tasks/info/drv_info.md
      - Información de configuración de Windows PE: img_tasks/info/winpe_info.md
  - Paquetes del sistema operativo:
    - Resumen: img_tasks/packages/pkgs.md
    - Añadir paquetes: img_tasks/packages/add_package.md
    - Eliminar paquetes: img_tasks/packages/remove_package.md
  - Características:
    - Overview: img_tasks/features/features.md
    - Enabling features: img_tasks/features/enable_feature.md
    - Disabling features: img_tasks/features/disable_feature.md
  - Paquetes AppX:
    - Overview: img_tasks/appx/appx.md
    - Adding AppX packages: img_tasks/appx/add_provisionedappxpackage.md
    - Removing AppX packages: img_tasks/appx/remove_provisionedappxpackage.md
  - Funcionalidades:
    - Overview: img_tasks/capabilities/caps.md
    - Adding capabilities: img_tasks/capabilities/add_capability.md
    - Removing capabilities: img_tasks/capabilities/remove_capability.md
  - Controladores:
    - Overview: img_tasks/drivers/drvs.md
    - Adding drivers: img_tasks/drivers/add_driver.md
    - Exporting drivers: img_tasks/drivers/export_driver.md
    - Removing drivers: img_tasks/drivers/remove_driver.md
  - Servicio de Windows PE:
    - Setting the target path: img_tasks/winpe/set_targetpath.md
    - Setting the scratch space: img_tasks/winpe/set_scratchspace.md
#  - Command-line help: img_tasks/cli_tools/cli_help
  - Herramientas:
    - Administrador de imágenes montadas: img_tasks/tools/mimgmgr.md
    - Conversión de imágenes: img_tasks/tools/wim2esd.md
    - Combinación de archivos SWM: img_tasks/tools/swm2wim.md
    - Editor de listas de configuración de DISM: img_tasks/tools/configlisteditor.md
- Herramientas de línea de comandos:
  - Resumen: cli_tools/cli_tools.md
  - Consola de comandos:
    - Resumen: cli_tools/cmd_console.md
    - Herramientas:
      - Ayuda de comandos: cli_tools/cmdhelp.md
      - Obtención extendida de paquetes AppX: cli_tools/extappx.md