site_name: DISMTools
theme: readthedocs
nav:
- Home: index.md
- Getting started: getting_started/start.md
- Image tasks:
  - Overview: img_tasks/img_tasks.md
  - Image management:
    - Overview: img_tasks/mgmt.md
    - Applying an image: img_tasks/mgmt/apply_image.md
    - Capturing an image: img_tasks/mgmt/capture_image.md
    - Removing volume images from an image file: img_tasks/mgmt/delete_image.md
    - Getting image information: img_tasks/mgmt/get_imginfo.md
    - Mounting an image: img_tasks/mgmt/mount_image.md
    - Remounting an image: img_tasks/mgmt/remount_image.md
    - Splitting an image: img_tasks/mgmt/split_image.md
    - Unmounting an image: img_tasks/mgmt/unmount_image.md
    - Image information:
      - Overview: img_tasks/info/infodlgs.md
  - OS packages:
    - Overview: img_tasks/packages/pkgs.md
    - Adding packages: img_tasks/packages/add_package.md
    - Getting package information: img_tasks/packages/get_pkginfo.md
    - Removing packages: img_tasks/packages/remove_package.md
  - Features:
    - Overview: img_tasks/features/features.md
    - Enabling features: img_tasks/features/enable_feature.md
    - Getting feature information: img_tasks/features/get_featinfo.md
    - Disabling features: img_tasks/features/disable_feature.md
  - AppX packages:
    - Overview: img_tasks/appx/appx.md
    - Adding AppX packages: img_tasks/appx/add_provisionedappxpackage.md
    - Getting AppX package information: img_tasks/appx/get_appxinfo.md
    - Removing AppX packages: img_tasks/appx/remove_provisionedappxpackage.md
  - Capabilities:
    - Overview: img_tasks/capabilities/caps.md
    - Adding capabilities: img_tasks/capabilities/add_capability.md
    - Getting capability information: img_tasks/capabilities/get_capabilityinfo.md
    - Removing capabilities: img_tasks/capabilities/remove_capability.md
  - Drivers:
    - Overview: img_tasks/drivers/drvs.md
    - Adding drivers: img_tasks/drivers/add_driver.md
    - Getting driver information: img_tasks/drivers/get_drvinfo.md
    - Removing drivers: img_tasks/drivers/remove_driver.md
    - Exporting drivers: img_tasks/drivers/export_driver.md
  - Windows PE servicing:
    - Getting Windows PE setting: img_tasks/winpe/get_pesettings.md
    - Setting the target path: img_tasks/winpe/set_targetpath.md
    - Setting the scratch space: img_tasks/winpe/set_scratchspace.md
  - Command-line help: img_tasks/cli_tools/cli_help
  - Tools:
    - Mounted image manager: img_tasks/tools/mimgmgr.md
    - Image conversion: img_tasks/tools/wim2esd.md
    - SWM file merger: img_tasks/tools/swm2wim.md
    - DISM Configuration List Editor: img_tasks/tools/wimscript_editor.md
- Command-line tools:
  - Overview: cli_tools/cli_tools.md
  - Command Console:
    - Overview: cli_tools/cmd_console.md
    - Tools:
      - Command help: cli_tools/cmdhelp.md
      - Mounted image manager (CLI version): cli_tools/mimgmgr.md
      - Extended AppX package getter: cli_tools/extappx.md