site_name: DISMTools
theme: readthedocs
nav:
- Home: index.md
- Getting started: getting_started/start.md
- Image tasks:
  - Overview: img_tasks/img_tasks.md
  - Online installation management mode: img_tasks/online_inst_mgmt.md
  - Offline installation management mode: img_tasks/offline_inst_mgmt.md
  - Image management:
    - Overview: img_tasks/mgmt.md
    - Applying an image: img_tasks/mgmt/apply_image.md
    - Capturing an image: img_tasks/mgmt/capture_image.md
    - Removing volume images from an image file: img_tasks/mgmt/delete_image.md
    - Mounting an image: img_tasks/mgmt/mount_image.md
    - Remounting an image: img_tasks/mgmt/remount_image.md
    - Splitting an image: img_tasks/mgmt/split_image.md
    - Unmounting an image: img_tasks/mgmt/unmount_image.md
    - Image information dialogs:
      - Overview: img_tasks/info/infodlgs.md
      - Image file information: img_tasks/info/img_info.md
      - Package information: img_tasks/info/pkg_info.md
      - Feature information: img_tasks/info/feat_info.md
      - AppX package information: img_tasks/info/appxpkg_info.md
      - Capability information: img_tasks/info/cap_info.md
      - Driver information: img_tasks/info/drv_info.md
      - Windows PE configuration information: img_tasks/info/winpe_info.md
  - OS packages:
    - Overview: img_tasks/packages/pkgs.md
    - Adding packages: img_tasks/packages/add_package.md
    - Removing packages: img_tasks/packages/remove_package.md
  - Features:
    - Overview: img_tasks/features/features.md
    - Enabling features: img_tasks/features/enable_feature.md
    - Disabling features: img_tasks/features/disable_feature.md
  - AppX packages:
    - Overview: img_tasks/appx/appx.md
    - Adding AppX packages: img_tasks/appx/add_provisionedappxpackage.md
    - Removing AppX packages: img_tasks/appx/remove_provisionedappxpackage.md
  - Capabilities:
    - Overview: img_tasks/capabilities/caps.md
    - Adding capabilities: img_tasks/capabilities/add_capability.md
    - Removing capabilities: img_tasks/capabilities/remove_capability.md
  - Drivers:
    - Overview: img_tasks/drivers/drvs.md
    - Adding drivers: img_tasks/drivers/add_driver.md
    - Removing drivers: img_tasks/drivers/remove_driver.md
    - Exporting drivers: img_tasks/drivers/export_driver.md
  - Windows PE servicing:
    - Setting the target path: img_tasks/winpe/set_targetpath.md
    - Setting the scratch space: img_tasks/winpe/set_scratchspace.md
  - Command-line help: img_tasks/cli_tools/cli_help
  - Tools:
    - Mounted image manager: img_tasks/tools/mimgmgr.md
    - Image conversion: img_tasks/tools/wim2esd.md
    - SWM file merger: img_tasks/tools/swm2wim.md
    - DISM Configuration List Editor: img_tasks/tools/configlisteditor.md
- Command-line tools:
  - Overview: cli_tools/cli_tools.md
  - Command Console:
    - Overview: cli_tools/cmd_console.md
    - Tools:
      - Command help: cli_tools/cmdhelp.md
      - Mounted image manager (CLI version): cli_tools/mimgmgr.md
      - Extended AppX package getter: cli_tools/extappx.md